# Numpy Intersection & Difference

In [2]:
import numpy as np

In [3]:
n1=np.array([10,20,30,40,50,60])

In [4]:
n2=np.array([50,60,70,80])

## Intersection (common values)

In [6]:
np.intersect1d(n1,n2)

array([50, 60])

## A - B  

In [7]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

## B - A

In [8]:
np.setdiff1d(n2,n1)

array([70, 80])

## UNION (sum of A + B)

In [9]:
np.union1d(n1,n2)

array([10, 20, 30, 40, 50, 60, 70, 80])