# *NUMPY MERGING*

In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3])

In [3]:
n2=np.array([4,5,6])

## Merging in horizontal

In [4]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

## Merging in vertical

In [5]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

## Merging column wise

In [6]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

## MERGING ROW WISE

In [7]:
np.row_stack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])